(function(){
  'use strict';
  const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let config,previousClues=null,toastTimer,bookTab='단서',bookSelected=0,lastFocus;
  function setup(value){config=value;document.title=config.caseId+' · '+config.title;$('#caseName').textContent=document.title;$('#brandCase').textContent=document.title;$('#caseObjective').textContent='현장과 진술을 대조해 사건의 전말을 밝히세요.';
    document.addEventListener('keydown',e=>{if($('#modal').classList.contains('hidden'))return;if(e.key==='Escape'){e.preventDefault();closeBook();}if(e.key==='Tab'){const nodes=[...$('#modal').querySelectorAll('button,a,input,select,summary,[tabindex="0"]')].filter(n=>!n.disabled&&n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
    $('#modalClose').addEventListener('click',closeBook);$('.modal-backdrop').addEventListener('click',closeBook);
  }
  function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
  function update(state){const ids=state.clues||[];if(previousClues!==null&&ids.length>previousClues)toast('새 단서 '+(ids.length-previousClues)+'개를 수첩에 기록했어요.');previousClues=ids.length;}
  function button(choice){const b=document.createElement('button');b.type='button';b.innerHTML=choice.label;b.disabled=!!choice.locked;b.dataset.action=choice.key||'';b.className=(choice.primary?'primary ':'')+(choice.locked?'locked ':'')+(choice.done?'done ':'');if(choice.image){const img=document.createElement('img');img.src=choice.image;img.alt='';img.className='action-art';b.querySelector('.choice-icon')?.remove();b.prepend(img);}b.addEventListener('click',()=>{if(!choice.locked)choice.run();});return b;}
  function render(model){document.body.dataset.scene=model.id;document.body.dataset.view=model.kind||'detail';$('.map').hidden=model.id==='intro';$('.game-stage').classList.toggle('interview-stage',!!model.person);$('#caseObjective').textContent=model.objective|| (model.person?'진술을 듣고 확보한 단서와 대조하세요.':model.id==='solve'?'누가, 왜, 어떻게 했는지 판단하세요.':model.id==='ending'?'사건 해결 · 추리와 기록을 돌아보세요.':'현장과 진술을 대조해 사건의 전말을 밝히세요.');
    $('#chapterLabel').textContent=model.label;$('#sceneKicker').textContent=config.caseId;$('#sceneTitle').innerHTML=model.title;$('#sceneLocation').textContent=model.location||config.title;
    $('#breadcrumb').textContent=config.caseId+'  /  '+(model.label||'수사 기록');$('#placeTitle').innerHTML=model.title;$('#sceneDescription').innerHTML='';$('#sceneGuide').innerHTML='';
    const temp=document.createElement('div');temp.innerHTML=model.html||'';const brief=temp.querySelector('.room-brief');if(brief){$('#sceneDescription').innerHTML=brief.querySelector('p:not(.room-brief__guide)')?.innerHTML||'';$('#sceneGuide').innerHTML=brief.querySelector('.room-brief__guide')?.innerHTML||'';brief.remove();}
    $('#sceneVisual').hidden=!model.image||!!model.person||model.id==='ending'||model.id==='solve';$('#sceneVisual').style.backgroundImage=model.image?`url('${model.image}')`:'none';$('#sceneVisual').style.backgroundPosition=model.position||'center';$('#hotspotLayer').replaceChildren();$('#spotActions').replaceChildren();
    (model.spots||[]).forEach((point,i)=>{const b=button({label:String(i+1),run:point.run,locked:point.locked,key:point.key});b.className='hotspot'+(point.done?' hotspot--found':'');b.style.setProperty('--x',point.x+'%');b.style.setProperty('--y',point.y+'%');b.setAttribute('aria-label',point.label+' '+(point.done?'다시 보기':'조사하기'));$('#hotspotLayer').append(b);const item=button({label:`<span class="number">${i+1}</span><span>${esc(point.label)}</span><small>${point.done?'✓ 확인함':'조사하기'}</small>`,run:point.run,locked:point.locked,key:point.key,done:point.done});$('#spotActions').append(item);});
    if(model.person){$('#sceneVisual').hidden=true;$('#placeTitle').hidden=true;$('#story').innerHTML=model.person;const list=document.createElement('div');list.className='question-list';(model.choices||[]).filter(c=>c.kind==='question').forEach(c=>{const card=document.createElement('div');card.className='question-card '+(c.locked?'locked':c.done?'done':'');card.dataset.question=c.key;const b=button(c);const status=document.createElement('span');status.className='question-status';status.textContent=c.locked?'🔒 잠김':c.done?'✓ 확인함':'질문하기';b.append(status);card.append(b);if(model.answer&&model.answer.key===c.key){const ans=document.createElement('div');ans.className='inline-answer';ans.innerHTML=model.answer.html;card.append(ans);}list.append(card);});$('#story').append(list);
    }else{$('#placeTitle').hidden=false;const first=temp.querySelector(':scope>h2');if(first&&first.innerHTML===model.title)first.remove();$('#story').innerHTML=temp.innerHTML;}
    $('#choices').replaceChildren();let group='';(model.choices||[]).filter(c=>!model.person||c.kind!=='question').forEach(c=>{if(c.group&&c.group!==group){const h=document.createElement('div');h.className='choice-group-heading';h.innerHTML=esc(c.group);$('#choices').append(h);group=c.group;}$('#choices').append(button(c));});
    $('#mapPlaces').replaceChildren();config.locations().forEach(p=>{const b=button({label:`<img src="${esc(p.image)}" alt=""><span><b>${esc(p.name)}</b><small>${p.visited?'방문함':'조사 가능'}</small></span>`,run:p.run,key:p.id});b.className='map-place';if(model.placeId===p.id)b.setAttribute('aria-current','location');$('#mapPlaces').append(b);});
    $('#mapLinks').replaceChildren();[['수사 본부로',config.hub],['인물 심문',openPeople],['최종 추리',config.solve]].forEach(([label,run])=>$('#mapLinks').append(button({label,run})));
    if(model.kind==='hub'){const paras=[...$('#story').children];const keep=paras.filter(n=>n.classList.contains('hub-progress'));const prose=paras.filter(n=>!keep.includes(n));const d=document.createElement('details');d.innerHTML='<summary>수사 브리핑 다시 읽기</summary>';prose.forEach(n=>d.append(n));$('#story').replaceChildren(...keep,d);$('#story').classList.add('hub-story');}else $('#story').classList.remove('hub-story');
    if(model.id==='ending'){const closed=$('#story .case-closed');if(closed){const img=document.createElement('img');img.src=config.detective;img.alt='사건을 해결한 탐정';const copy=document.createElement('div');while(closed.firstChild)copy.append(closed.firstChild);closed.append(img,copy);}const children=[...$('#story').children],firstH=children.findIndex(n=>n.tagName==='H3');if(firstH>=0){const detail=document.createElement('details');detail.className='ending-details';detail.innerHTML='<summary>사건의 전말과 상세 해설</summary><div></div>';children.slice(firstH).forEach(n=>detail.lastElementChild.append(n));$('#story').append(detail);}}
    update(model.state);if(document.activeElement===document.body||document.activeElement?.classList.contains('skip-link')){const target=model.person?$('#story h2'):$('#placeTitle');target.tabIndex=-1;target.focus({preventScroll:true});}if(model.answer){requestAnimationFrame(()=>$('.inline-answer')?.scrollIntoView({block:'nearest',behavior:'smooth'}));}else window.scrollTo({top:0,behavior:'instant'});
  }
  function enhanceSolve(){const form=$('#solveForm');if(!form||form.querySelector('.solve-steps'))return;$('.map').hidden=true;document.body.dataset.view='solve';const repeat=$('#story').querySelector(':scope>h2');if(repeat&&repeat.innerHTML===$('#placeTitle').innerHTML)repeat.remove();const thought=$('#story').querySelector(':scope>.detective-thought');if(thought){const detail=document.createElement('details');detail.className='thinking-details';detail.innerHTML='<summary>추리할 때 유의할 점</summary>';thought.before(detail);detail.append(thought);}const fields=[...form.querySelectorAll('.question')];if(fields.length!==3)return;let current=0;const steps=document.createElement('nav');steps.className='solve-steps';steps.setAttribute('aria-label','추리 단계');const nav=document.createElement('div');nav.className='solve-nav';const prev=button({label:'← 이전 판단',run:()=>show(current-1)}),next=button({label:'다음 판단 →',run:()=>show(current+1)});nav.append(prev,next);const submit=form.querySelector('[type=submit]');submit.textContent='세 판단 모두 제출하기';submit.classList.add('primary');
    function show(i,focus=true){current=Math.max(0,Math.min(2,i));fields.forEach((f,j)=>f.hidden=j!==current);steps.querySelectorAll('button').forEach((b,j)=>{b.setAttribute('aria-current',j===current?'step':'false');const answer=fields[j].querySelector('input:checked'),evidence=fields[j].querySelector('select');b.querySelector('.step-check').textContent=answer&&(!evidence||evidence.value)?'선택함':'미선택';});prev.disabled=current===0;next.hidden=current===2;submit.hidden=current!==2;if(focus){fields[current].tabIndex=-1;fields[current].focus({preventScroll:true});}}
    ['누가','왜','어떻게'].forEach((t,i)=>{const b=button({label:`${i+1}. ${t}<span class="step-check">미선택</span>`,run:()=>show(i)});steps.append(b);});form.prepend(steps);submit.before(nav);form.addEventListener('change',()=>show(current,false));form.addEventListener('keydown',e=>{if(e.key==='Enter'&&current<2&&e.target.tagName!=='BUTTON'){e.preventDefault();show(current+1);}});show(0,false);
  }
  function closeBook(){$('#modal').classList.add('hidden');$('.app-shell').inert=false;document.body.style.overflow='';lastFocus?.focus();}
  function openBook(tab='단서'){bookTab=tab;bookSelected=0;lastFocus=document.activeElement;$('#modal').classList.remove('hidden');$('.app-shell').inert=true;document.body.style.overflow='hidden';$('#modal').setAttribute('aria-label','수사수첩');$('#modalClose').setAttribute('aria-label','수첩 닫기');renderBook();$('#modalClose').focus();}
  function openPeople(){openBook('인물');$('#modal').setAttribute('aria-label','인물 심문');$('#modalClose').setAttribute('aria-label','인물 선택 닫기');$('#modalContent').innerHTML='<h2 class="book-heading">인물 심문</h2><p class="book-subtitle">확인할 인물을 선택하세요. 확보한 단서에 따라 새로운 질문이 열립니다.</p><div class="choices interview-picker" aria-label="심문할 인물 선택"></div>';config.people().forEach(person=>{const b=button({label:`<span class="choice-copy"><span class="choice-title">${esc(person.name)}</span><span class="choice-desc">${esc(person.role)}</span></span>`,image:person.image,key:'interview_'+person.id,run:()=>{closeBook();person.run();}});$('.interview-picker').append(b);});}
  function renderBook(){const data=config.records();const tabs=['단서','인물','장소','진술','시간선'];$('#modalContent').innerHTML=`<h2 class="book-heading">수사수첩</h2><p class="book-subtitle">${esc(config.caseId)} · ${esc(config.title)} · 단서 ${data.clues.length}개 확보</p><div class="book-tabs" role="tablist" aria-label="수첩 분류"></div><div id="bookPanel" role="tabpanel" aria-label="${esc(bookTab)}"></div>`;tabs.forEach(t=>{const b=button({label:t,run:()=>{bookTab=t;bookSelected=0;renderBook();$(`[data-tab="${t}"]`).focus();}});b.dataset.tab=t;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(bookTab===t));$('.book-tabs').append(b);});const panel=$('#bookPanel');
    if(bookTab==='시간선'){panel.innerHTML='<ol class="timeline-mini">'+data.timeline.map(t=>`<li><b>${esc(t.time)}</b><span>${t.html||esc(t.text)}</span></li>`).join('')+'</ol>';return;}
    if(bookTab==='진술'){panel.innerHTML=data.statements.length?'<div class="book-statements">'+data.statements.map(s=>`<article class="statement-card"><small>${esc(s.name)}</small><h3>${s.question}</h3>${s.html}</article>`).join('')+'</div>':'<p class="empty">아직 확인한 진술이 없습니다. 인물에게 질문해보세요.</p>';return;}
    const original=bookTab==='인물'?data.people:bookTab==='장소'?data.places:data.clues;panel.innerHTML=(bookTab==='단서'?'<input class="book-search" aria-label="확보한 단서 검색" placeholder="제목이나 내용으로 단서 찾기">':'')+'<div class="book-grid"><div class="book-list" role="listbox" aria-label="'+esc(bookTab)+' 목록"></div><article class="book-detail" id="bookDetail"></article></div>';
    function fillList(query=''){const items=original.filter(x=>!query||(x.name+' '+(x.text||'')).includes(query));if(!items.length){$('.book-list').innerHTML='';$('#bookDetail').innerHTML='<p class="empty">'+(query?'검색 결과가 없습니다.':'아직 확보한 단서가 없습니다. 현장을 조사해보세요.')+'</p>';return;}bookSelected=Math.min(bookSelected,items.length-1);$('.book-list').replaceChildren();items.forEach((item,i)=>{const b=button({label:(item.image?`<img src="${esc(item.image)}" alt="">`:'')+`<span><b>${esc(item.name)}</b>${item.role?`<small>${esc(item.role)}</small>`:''}</span>`,run:()=>{bookSelected=i;fillList(query);if(innerWidth<=700)$('#bookDetail').scrollIntoView({block:'start',behavior:'smooth'});}});b.className='book-item';b.setAttribute('role','option');b.setAttribute('aria-selected',String(bookSelected===i));$('.book-list').append(b);});const item=items[bookSelected];$('#bookDetail').innerHTML=(item.image?`<img class="book-detail-image ${bookTab==='인물'?'person-image':''}" src="${esc(item.image)}" alt="${esc(item.name)}">`:'')+`<span>${esc(item.role||bookTab)}</span><h3>${esc(item.name)}</h3>${item.html||`<p>${esc(item.text)}</p>`}`;}
    fillList();$('.book-search')?.addEventListener('input',e=>{bookSelected=0;fillList(e.target.value.trim());});
  }
  window.TheatreUI={setup,render,openBook,closeBook,enhanceSolve,toast,escape:esc};
})();
